services:
  - type: web
    name: uwear-virtual-try-on
    env: python
    buildCommand: cd ../frontend && npm ci && npm run build && cd ../backend && pip install -r requirements.txt
    startCommand: python simple_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: NODE_VERSION
        value: 18.0.0
    healthCheckPath: /startup
    autoDeploy: true
